services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: bootstrapper/Api/Dockerfile
      
  eshopdb:
    image: postgres:16-alpine

  seq:
    image: datalust/seq:latest

  redis:
    image: redis:alpine
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4

volumes:
  postgres_eshopdb:
  seq_data:
  rabbitmq_data:
  redis_data: