version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: bootstrapper/Api/Dockerfile
      
  eshopdb:
    image: postgres:16-alpine

  seq:
    image: datalust/seq:latest

  redis:
    image: redis:latest
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
# This must be separated from the image property
volumes:
  postgres_eshopdb:
  rabbitmq_data: