services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      # Database and Cache
      - ConnectionStrings__Database=Host=eshopdb;Port=5432;Database=eshopdb;Username=postgres;Password=postgres;
      - ConnectionStrings__Redis=redis:6379
      # RabbitMQ Configuration
      - MessageBroker__Host=rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      # Keycloak Identity Provider Configuration (Internal Docker Network)
      - Identity__Authority=http://keycloak:8080/realms/eshop-realm
      - Identity__RequireHttpsMetadata=false
      - keycloak__auth-server-url=http://keycloak:8080/
      - keycloak__ssl-required=none
      # Override Serilog to point to the Seq container
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - eshopdb
      - rabbitmq
      - redis
      - seq
      - keycloak

  eshopdb:
    container_name: eshopdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eshopdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=AdminPassword123!
    restart: always
    ports:
      - "5344:5341"
      - "9091:80"
    volumes:
      - seq_data:/data

  redis:
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    container_name: eshop_rabbitmq
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  keycloak:
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # Database Configuration
      - KC_DB=postgres
      - KC_DB_URL_HOST=eshopdb
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=eshopdb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB_SCHEMA=identity
    ports:
      - "9090:8080" # Accessible via http://localhost:9090 externally
    depends_on:
      - eshopdb

volumes:
  postgres_eshopdb:
  seq_data:
  rabbitmq_data: